// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohjkmsefimbqanjnkdca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oamttc2VmaW1icWFuam5rZGNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDMxNjIsImV4cCI6MjA2OTk3OTE2Mn0.V33HJVrA6DjIYck6X60aGrg93IJCYpdeuK88flybwGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});